[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
ggez = "0.9"
glam = "0.25"
image = "0.24"

# [dependencies.specs]
# version = "0.20"
# features = ["derive"]

[dependencies.protocol]
path = "../protocol"