//! An attempt at a basic ui system.

use ggez::input::keyboard::KeyCode;



pub struct UI {

}
impl UI{
 pub fn new() {
  println!("UI")
 }

 pub fn feed_key_event(&mut self, key_event: &KeyCode){
  match key_event {
    KeyCode::Key1 => todo!(),
    KeyCode::Key2 => todo!(),
    KeyCode::Key3 => todo!(),
    KeyCode::Key4 => todo!(),
    KeyCode::Key5 => todo!(),
    KeyCode::Key6 => todo!(),
    KeyCode::Key7 => todo!(),
    KeyCode::Key8 => todo!(),
    KeyCode::Key9 => todo!(),
    KeyCode::Key0 => todo!(),
    KeyCode::A => todo!(),
    KeyCode::B => todo!(),
    KeyCode::C => todo!(),
    KeyCode::D => todo!(),
    KeyCode::E => todo!(),
    KeyCode::F => todo!(),
    KeyCode::G => todo!(),
    KeyCode::H => todo!(),
    KeyCode::I => todo!(),
    KeyCode::J => todo!(),
    KeyCode::K => todo!(),
    KeyCode::L => todo!(),
    KeyCode::M => todo!(),
    KeyCode::N => todo!(),
    KeyCode::O => todo!(),
    KeyCode::P => todo!(),
    KeyCode::Q => todo!(),
    KeyCode::R => todo!(),
    KeyCode::S => todo!(),
    KeyCode::T => todo!(),
    KeyCode::U => todo!(),
    KeyCode::V => todo!(),
    KeyCode::W => todo!(),
    KeyCode::X => todo!(),
    KeyCode::Y => todo!(),
    KeyCode::Z => todo!(),
    KeyCode::Escape => todo!(),
    KeyCode::F1 => todo!(),
    KeyCode::F2 => todo!(),
    KeyCode::F3 => todo!(),
    KeyCode::F4 => todo!(),
    KeyCode::F5 => todo!(),
    KeyCode::F6 => todo!(),
    KeyCode::F7 => todo!(),
    KeyCode::F8 => todo!(),
    KeyCode::F9 => todo!(),
    KeyCode::F10 => todo!(),
    KeyCode::F11 => todo!(),
    KeyCode::F12 => todo!(),
    KeyCode::F13 => todo!(),
    KeyCode::F14 => todo!(),
    KeyCode::F15 => todo!(),
    KeyCode::F16 => todo!(),
    KeyCode::F17 => todo!(),
    KeyCode::F18 => todo!(),
    KeyCode::F19 => todo!(),
    KeyCode::F20 => todo!(),
    KeyCode::F21 => todo!(),
    KeyCode::F22 => todo!(),
    KeyCode::F23 => todo!(),
    KeyCode::F24 => todo!(),
    KeyCode::Snapshot => todo!(),
    KeyCode::Scroll => todo!(),
    KeyCode::Pause => todo!(),
    KeyCode::Insert => todo!(),
    KeyCode::Home => todo!(),
    KeyCode::Delete => todo!(),
    KeyCode::End => todo!(),
    KeyCode::PageDown => todo!(),
    KeyCode::PageUp => todo!(),
    KeyCode::Left => todo!(),
    KeyCode::Up => todo!(),
    KeyCode::Right => todo!(),
    KeyCode::Down => todo!(),
    KeyCode::Back => todo!(),
    KeyCode::Return => todo!(),
    KeyCode::Space => todo!(),
    KeyCode::Compose => todo!(),
    KeyCode::Caret => todo!(),
    KeyCode::Numlock => todo!(),
    KeyCode::Numpad0 => todo!(),
    KeyCode::Numpad1 => todo!(),
    KeyCode::Numpad2 => todo!(),
    KeyCode::Numpad3 => todo!(),
    KeyCode::Numpad4 => todo!(),
    KeyCode::Numpad5 => todo!(),
    KeyCode::Numpad6 => todo!(),
    KeyCode::Numpad7 => todo!(),
    KeyCode::Numpad8 => todo!(),
    KeyCode::Numpad9 => todo!(),
    KeyCode::NumpadAdd => todo!(),
    KeyCode::NumpadDivide => todo!(),
    KeyCode::NumpadDecimal => todo!(),
    KeyCode::NumpadComma => todo!(),
    KeyCode::NumpadEnter => todo!(),
    KeyCode::NumpadEquals => todo!(),
    KeyCode::NumpadMultiply => todo!(),
    KeyCode::NumpadSubtract => todo!(),
    KeyCode::AbntC1 => todo!(),
    KeyCode::AbntC2 => todo!(),
    KeyCode::Apostrophe => todo!(),
    KeyCode::Apps => todo!(),
    KeyCode::Asterisk => todo!(),
    KeyCode::At => todo!(),
    KeyCode::Ax => todo!(),
    KeyCode::Backslash => todo!(),
    KeyCode::Calculator => todo!(),
    KeyCode::Capital => todo!(),
    KeyCode::Colon => todo!(),
    KeyCode::Comma => todo!(),
    KeyCode::Convert => todo!(),
    KeyCode::Equals => todo!(),
    KeyCode::Grave => todo!(),
    KeyCode::Kana => todo!(),
    KeyCode::Kanji => todo!(),
    KeyCode::LAlt => todo!(),
    KeyCode::LBracket => todo!(),
    KeyCode::LControl => todo!(),
    KeyCode::LShift => todo!(),
    KeyCode::LWin => todo!(),
    KeyCode::Mail => todo!(),
    KeyCode::MediaSelect => todo!(),
    KeyCode::MediaStop => todo!(),
    KeyCode::Minus => todo!(),
    KeyCode::Mute => todo!(),
    KeyCode::MyComputer => todo!(),
    KeyCode::NavigateForward => todo!(),
    KeyCode::NavigateBackward => todo!(),
    KeyCode::NextTrack => todo!(),
    KeyCode::NoConvert => todo!(),
    KeyCode::OEM102 => todo!(),
    KeyCode::Period => todo!(),
    KeyCode::PlayPause => todo!(),
    KeyCode::Plus => todo!(),
    KeyCode::Power => todo!(),
    KeyCode::PrevTrack => todo!(),
    KeyCode::RAlt => todo!(),
    KeyCode::RBracket => todo!(),
    KeyCode::RControl => todo!(),
    KeyCode::RShift => todo!(),
    KeyCode::RWin => todo!(),
    KeyCode::Semicolon => todo!(),
    KeyCode::Slash => todo!(),
    KeyCode::Sleep => todo!(),
    KeyCode::Stop => todo!(),
    KeyCode::Sysrq => todo!(),
    KeyCode::Tab => todo!(),
    KeyCode::Underline => todo!(),
    KeyCode::Unlabeled => todo!(),
    KeyCode::VolumeDown => todo!(),
    KeyCode::VolumeUp => todo!(),
    KeyCode::Wake => todo!(),
    KeyCode::WebBack => todo!(),
    KeyCode::WebFavorites => todo!(),
    KeyCode::WebForward => todo!(),
    KeyCode::WebHome => todo!(),
    KeyCode::WebRefresh => todo!(),
    KeyCode::WebSearch => todo!(),
    KeyCode::WebStop => todo!(),
    KeyCode::Yen => todo!(),
    KeyCode::Copy => todo!(),
    KeyCode::Paste => todo!(),
    KeyCode::Cut => todo!(),
  }
 }

}